flask_module/customadmin/users/__init__.py
from .routes import users

flask_module/customadmin/users/routes.py
from ..utiles import *
from flask import render_template, redirect, request, url_for, Blueprint
from flask_login import current_user
from flask_module.customadmin.users.forms import *
from flask_module.user.models import *
from flask_module import bcrypt 
import secrets, os

users = Blueprint("users", __name__, url_prefix="/user")

@users.route("/add_user", methods=["POST", "GET"])
@login_required
@superuser_required
def add_user():
    form = CustomadminAddUserForm()
    form.role.choices = [role.name for role in Role.query.all()]
    if request.method == "POST":
        if form.validate_on_submit():
            role = Role.query.filter_by(name=form.role.data).first()
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
            if form.profile_picture.data:
                hex_image = secrets.token_hex(8)
                f_name, f_ext = os.path.splitext(form.profile_picture.data.filename)
                image_name = hex_image + f_ext
                image_path = os.path.join(app.root_path, 'static\images', image_name)
                form.profile_picture.data.save(image_path)
                user = User(username=form.username.data, email=form.email.data, profile_picture=image_name, password=hashed_password, role_id=role.id)
            else:
                user = User(username=form.username.data, email=form.email.data, password=hashed_password, role_id=role.id)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('customadmin.dashboard', username=current_user.username))
    return render_template("customadmin/users/add_user.html", form=form)


@users.route("/<int:user_id>/user_update", methods=["POST", "GET"])
@login_required
@superuser_required
def user_update(user_id):
    form = CustomadminEditUserForm()
    user = User.query.filter_by(id=int(user_id)).first()
    form.role.choices = [role.name for role in Role.query.all()]
    if request.method == "POST":
        if form.validate_on_submit():
            if form.profile_picture.data:
                hex_image = secrets.token_hex(8)
                f_name, f_ext = os.path.splitext(form.profile_picture.data.filename)
                image_name = hex_image + f_ext
                image_path = os.path.join(app.root_path, 'static\images', image_name)
                form.profile_picture.data.save(image_path)
                user.profile_picture = image_name
            user.username = form.username.data
            user.email = form.email.data
            role = Role.query.filter_by(name=form.role.data).first()
            user.role = role
            db.session.commit()
            return redirect(url_for("customadmin.dashboard", username=current_user.username))
    else:
        form.username.data = user.username  
        form.email.data = user.email
        form.profile_picture.data = user.profile_picture
        form.role.data = user.role.name
        return render_template("customadmin/users/update_user.html", user=user, form=form)


@users.route("/<int:user_id>/user_detail")
@login_required
def user_detail(user_id):
    user = User.query.filter_by(id=user_id).first()
    return render_template("customadmin/users/user_detail.html", user=user)


@users.route("/<int:user_id>/delete_user")
@login_required
@superuser_required
def delete_user(user_id):
    user = User.query.filter_by(id=int(user_id)).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("customadmin.dashboard", username=current_user.username))

flask_module/posts/routes.py
from ast import Delete
from flask import Blueprint, render_template, url_for, request, redirect, session
from flask_login import current_user
from flask_module.posts.form import AddPost
from flask_module import app, db
from flask_module.posts.models import Post, Comments, Likes
from flask_module.user.models import User
import os, secrets






post = Blueprint("post", __name__)

@post.route("/posts")
def posts():
    if "user" in session:
        page  = request.args.get('page', 1, type=int)
        connected_user_id_list = [user.id for user in current_user.following]
        posts = Post.query.filter(Post.user_id.in_(connected_user_id_list)).paginate(per_page=2, page=page)
        return render_template("posts/all_posts.html", posts=posts)
    else:
        return redirect(url_for("user.login"))

@post.route("/add_post", methods=['POST', 'GET'])
def add_post():
    form = AddPost()
    if "user" in session:
        if request.method == "POST":
            if form.validate_on_submit:
                if form.image.data:
                    hex_image = secrets.token_hex(8)
                    f_name, f_ext = os.path.splitext(form.image.data.filename)
                    image_name = hex_image + f_ext
                    image_path = os.path.join(app.root_path, 'static\images', image_name)
                    form.image.data.save(image_path)
                    post = Post(image=image_name, caption=form.caption.data, user_id=current_user.id, )
                else:
                    post = Post(caption=form.caption.data, user_id=current_user.id)
                db.session.add(post)
                db.session.commit()
                return redirect(url_for("user.profile", username=current_user.username))
        return render_template("posts/add_post.html", form=form)
    else:
        return redirect(url_for("user.login"))


@post.route("/update_post/<int:post_id>", methods=['POST', 'GET'])
def update_post(post_id):
    form = AddPost()
    post = Post.query.filter_by(id=int(post_id)).first()
    if "user" in session:
        if request.method == 'POST':
            if form.validate_on_submit:
                if form.image.data:
                    hex_image = secrets.token_hex(8)
                    f_name, f_ext = os.path.splitext(form.image.data.filename)
                    image_name = hex_image + f_ext
                    image_path = os.path.join(app.root_path, 'static\images', image_name)
                    form.image.data.save(image_path)
                    post.image = image_name
                post.caption = form.caption.data
                post.user_id = current_user.id
                db.session.commit()
                return redirect(url_for("user.profile", username=current_user.username))
        else:
            form.caption.data = post.caption
            return render_template("posts/update_post.html", post=post, form=form)
    else:
        return redirect(url_for("user.login"))


@post.route("/post_detail/<int:post_id>", methods=['POST', 'GET'])
def post_detail(post_id):
    if "user" in session:
        post = Post.query.filter_by(id=int(post_id)).first()
        comments = Comments.query.filter_by(post_id=int(post_id))
        return render_template("posts/post_detail.html", post=post, comments=comments)
    else:
        return redirect(url_for("user.login"))


@post.route("/delete_post/<int:post_id>")
def delete_post(post_id):
    if "user" in session:
        post = Post.query.filter_by(id=int(post_id)).first()
        db.session.delete(post)
        db.session.commit()
        return redirect(url_for("user.profile", username=current_user.username))
    else:
        return redirect(url_for("user.login"))
    
    
@post.route('/add_comment/<int:post_id>', methods=['POST', 'GET'])
def add_comment(post_id):
    comment = Comments(user_id=current_user.id, post_id=post_id , comment=request.form['comment'])
    db.session.add(comment)
    db.session.commit()
    return redirect(url_for("user.profile", username=current_user.username))


@post.route("/like/<int:post_id>", methods=['POST', 'GET'])
def like_a_post(post_id):
    like = Likes(user_id=current_user.id, post_id=int(post_id))
    db.session.add(like)
    db.session.commit()
    return redirect(url_for("post.posts"))


@post.route("/dislike/<int:like_id>", methods=['POST', 'GET'])
def dislike(like_id):
    like = Likes.query.filter_by(id=like_id).first()
    db.session.delete(like)
    db.session.commit()
    return redirect(url_for("post.posts")) 

flask_module/user/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, session, jsonify, abort
from flask_module.user.forms import RegistraionForm, LoginForm, ResetPasswordEmailForm, ResetPassword
from flask_module.user.models import User, Role
from flask_module.posts.models import Post
from flask_login import current_user, login_user, logout_user
from flask_module import bcrypt, db, app, mail
from bs4 import BeautifulSoup
from flask_mail import Message
import secrets, os, requests, base64, random

user = Blueprint("user", __name__)

# db.drop_all()
# db.create_all()

@user.route("/")
@user.route("/index")
def home():
    db.create_all()
    # db.drop_all()
    if "user" in session:
        loged_in_user = session['user']
        return redirect(url_for('user.profile', username=loged_in_user))
    else:
        return render_template("home.html")
    

@user.route("/register", methods=["POST", "GET"])
def register():
    form = RegistraionForm()
    if "user" in session:
        loged_in_user = session['user']
        return redirect(url_for('user.profile', username=loged_in_user))
    else:
        if form.validate_on_submit():
            role = Role.query.filter_by(name="User").first()
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
            if form.profile_picture.data:
                hex_image = secrets.token_hex(8)
                f_name, f_ext = os.path.splitext(form.profile_picture.data.filename)
                image_name = hex_image + f_ext
                image_path = os.path.join(app.root_path, 'static\images', image_name)
                form.profile_picture.data.save(image_path)
                user = User(username=form.username.data, email=form.email.data, profile_picture=image_name, password=hashed_password, role_id=role.id)
            else:
                user = User(username=form.username.data, email=form.email.data, password=hashed_password, role_id=role.id)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        return render_template("user/register.html", form=form)


@user.route("/login", methods=["POST", "GET"])
def login():
    form = LoginForm()
    if "user" in session:
        loged_in_user = session['user']
        return redirect(url_for('user.profile', username=loged_in_user))
    else:
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                session['user'] = user.username
                return redirect(url_for("user.profile", username=user.username))
        return render_template("user/login.html", form=form)


@user.route("/logout")
def logout():
    logout_user()
    session.pop("user", None)
    return redirect(url_for("user.login"))


@user.route("/profile/<string:username>", methods=["POST", "GET"])
def profile(username):
    page  = request.args.get('page', 1, type=int)
    if "user" in session:
        user = User.query.filter_by(username=username).first()
        post = Post.query.filter_by(user_id=user.id).paginate(per_page=2, page=page)
        return render_template("user/profile.html", user=user, posts=post)
    else:
        return redirect(url_for("user.login"))


@user.route("/<int:user_id>/update", methods=["POST", "GET"])
def update(user_id):
    user = User.query.filter_by(id=user_id).first()
    form = RegistraionForm()
    if "user" in session:
        if request.method == "POST":
            if form.validate_on_submit:
                if form.profile_picture.data:
                    hex_image = secrets.token_hex(8)
                    f_name, f_ext = os.path.splitext(form.profile_picture.data.filename)
                    image_name = hex_image + f_ext
                    image_path = os.path.join(app.root_path, 'static\images', image_name)
                    form.profile_picture.data.save(image_path)
                    user.profile_picture = image_name
                user.username = form.username.data
                user.email = form.email.data
                db.session.commit()
                return redirect(url_for("user.profile", username=user.username))
        else:
            form.username.data = user.username
            form.email.data = user.email
            form.profile_picture.data = user.profile_picture
            form.submit.label.text = "Update Profile"
            return render_template("user/update_profile.html", user=user, form=form)
    else:
        return redirect(url_for("user.login"))
    

@user.route("/users", methods=['POST', 'GET'])
def users():
    if "user" in session:
        page  = request.args.get('page', 1, type=int)
        users = User.query.filter(User.id != current_user.id).paginate(per_page=1, page=page)
        return render_template("user/all_users.html", users=users)
    else:
        abort(401)
        # return redirect(url_for("user.login"))


@user.route("/profile_detail/<string:username>", methods=["POST", "GET"])
def profile_detail(username):
    page  = request.args.get('page', 1, type=int)
    if "user" in session:
        user = User.query.filter_by(username=username).first()
        post = Post.query.filter_by(user_id=user.id).paginate(per_page=2, page=page)
        return render_template("user/profile_detail.html", user=user, posts=post)
    else:
        return redirect(url_for("user.login"))
    

@user.route("/follow_user/<int:user_id>", methods=["POST", "GET"])
def follow_user(user_id):
    authenticated_user = User.query.filter_by(id=current_user.id).first()
    user = User.query.filter_by(id=user_id).first()
    authenticated_user.following.append(user)
    db.session.commit()
    return redirect(url_for('user.users'))


@user.route("/remove_user/<int:user_id>", methods=["POST", "GET"])
def remove_user(user_id):
    authenticated_user = User.query.filter_by(id=current_user.id).first()
    user = User.query.filter_by(id=user_id).first()
    authenticated_user.following.remove(user)
    db.session.commit()
    return redirect(url_for('user.users'))


@user.route('/scrape_images')
def scrape_images():
    url = request.args.get('url')
    req = requests.get(url)
    soup = BeautifulSoup(req.text, 'html.parser')
    images = soup.find_all('img')
    
    img_scr = []
    for img in images:
        if img['src'][0] == "/":
            img['src'] = "https:" + img['src']
        img_scr.append(img['src'])
    print(img_scr)
    return jsonify(img_scr)


@user.route('/post_scraped_image/', methods=["POST", "GET"])
def post_scraped_image():
    src_ = request.args.get('src')
    src = base64.b64decode(src_).decode('ascii')
    hex_image = secrets.token_hex(8)
    f_name, f_ext = os.path.splitext(src)
    image_name = hex_image + ".jpg"
    image_path = os.path.join(app.root_path, 'static\images', image_name)
    with open(image_path, 'wb') as f:
        im = requests.get(src)
        f.write(im.content)
    post = Post(image=image_name, caption="", user_id=current_user.id)
    db.session.add(post)
    db.session.commit()
    return redirect(url_for("user.profile", username=current_user.username))


@user.route('/post_scraped', methods=["POST", "GET"])
def post_scraped():
    src = request.args.get('src')
    hex_image = secrets.token_hex(8)
    f_name, f_ext = os.path.splitext(src)
    image_name = hex_image + ".jpg"
    image_path = os.path.join(app.root_path, 'static\images', image_name)
    with open(image_path, 'wb') as f:
        im = requests.get(src)
        f.write(im.content)
    post = Post(image=image_name, caption="", user_id=current_user.id)
    db.session.add(post)
    db.session.commit()
    return jsonify(src)


def send_mail(user):
    token = user.generet_reset_password_token()
    msg = Message("Password Reset Request", sender="noreply@demo.com", recipients=[user.email])
    msg.body = f"""
    To reset your password, visit following link.
    {url_for("user.reset_password", token=token, _external=True)}
    """
    mail.send(msg)


@user.route("/reset_password_request", methods=["GET", "POST"])
def reset_password_request():
    form = ResetPasswordEmailForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        code = random.choice(range(100000, 999999))
        print(code)
        send_mail(user)
        return redirect(url_for("user.login"))
        # token = User.generet_reset_password_token(user)
        
        # return redirect(url_for("user.reset_password", token=token))
    return render_template("user/reset_password_request.html", form=form)


@user.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_password(token):
    user = User.verify_password_token(token)
    if user is None:
        return redirect("user.reset_password_request")
    form = ResetPassword()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user.password = hashed_password
        db.session.commit()
        return redirect(url_for("user.login"))
    return render_template("user/reset_password.html", form=form, token=token)

flask_module/templates/user/all_users.html
{% extends "base.html" %}

{% block title %}
<title>Users</title>
{% endblock title %}

{% block contant %}
<h1 class="m-5">All Users</h1>
{% for user in users %}
<div class="container m-5 d-flex">
    <img src="{{ url_for('static', filename='images/'+user.profile_picture) }}" alt="" class="w-25 h-25">
    <div class="ml-5">
        <h3>{{user.username}}</h3>
        <p>{{user.email}}</p>
        {% if user in current_user.following %}
        <a href="{{ url_for('user.remove_user', user_id=user.id) }}" class="btn btn-danger">Remove Following</a>
        {% else %}
        <a href="{{ url_for('user.follow_user', user_id=user.id) }}" class="btn btn-primary">Connect</a>
        {% endif %}
        <a href="{{ url_for('user.profile_detail', username=user.username) }}" class="btn btn-warning">View Profile</a>
    </div>
</div>
{% endfor %}

<div class="my-5 text-center">
    {% for page_num in users.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
            {% if users.page == page_num %}
                <a href="{{ url_for('user.users', page=page_num) }}" class="btn btn-info">{{page_num}}</a>
            {% else %}
                <a href="{{ url_for('user.users', page=page_num) }}" class="btn btn-outline-info">{{page_num}}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
</div>
{% endblock contant %}

flask_module/templates/user/login.html
{% extends "base.html" %}

{% block title %}
<title>Log in</title>
{% endblock title %}

{% block navbar %}
{% endblock navbar %}

{% block contant %}
<div class="container m-auto">
    <h3 class="text-center mt-5">Log in</h3>
    <form method="POST" action="{{ url_for('user.login') }}" novalidate>
        {{form.hidden_tag()}}
        <div class="text-center mt-3">
            <div class="text-center mt-3">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control mt-2 is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control mt-2", attr="required=False") }}
                {% endif %}
            </div>
        </div>
        <div class="text-center mt-3">
            <div class="text-center mt-3">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control mt-2 is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control mt-2", attr="required=False") }}
                {% endif %}
            </div>
        </div>
        <div class="text-center mt-3">
            {{ form.submit(class="btn btn-success mt-2") }}
        </div> 
    </form>
    <p class="text-center mt-2"><a href="{{ url_for('user.reset_password_request') }}">Forget Password.</a></p>
    <p class="text-center mt-5">Not register yet? Please <a href="{{ url_for('user.register') }}">Register</a> first.</p>
</div>
{% endblock contant %}

flask_module/templates/user/profile.html
{% extends "base.html" %}

{% block title %}
<title>Profile {{current_user.username}}</title>
{% endblock title %}

{% block contant %}
<div class="container m-5 d-flex">
    <img src="{{ url_for('static', filename='images/'+current_user.profile_picture) }}" alt="" class="w-25 h-25">
    <div class="ml-5">
        <h3>{{current_user.username}}</h3>
        <p>{{current_user.email}}</p>
        <a href="{{ url_for('user.update', user_id=user.id) }}" class="btn btn-info">Update</a>
        <a href="{{ url_for('post.add_post') }}" class="btn btn-secondary">Add Post</a>
    </div>
</div>

<div class="m-auto w-75">
    <h1 class="m-auto">{{current_user.username}}'s Posts</h1>
    {% for post in posts %}
    <div class="jumbotron mt-3 d-flex">
        <img src="{{ url_for('static', filename='images/'+post.image) }}" alt="" class="w-25 h-25">
        <div class="ml-5">
            <p class="lead">{{ post.caption }}</p>
            <hr class="my-4">
            <p>{{ post.created_at }}</p>
            <p>Likes : {{ post.likes|length }}</p>
            <p class="lead">
              <a class="btn btn-dark btn-lg" href="{{ url_for('post.update_post', post_id=post.id) }}" role="button">Edit</a>
              <a class="btn btn-danger btn-lg delete-post" data-postid="{{post.id}}" href="javascript:void(0);" role="button">Delete</a>
            </p>
            <hr class="my-4">
            <h4>Comments :</h4>
            {% for comment in post.comment[0:2] %}
            <h6 class="mt-2">{{comment.user.username}}</h6>
            <p>{{comment.comment}}</p>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</div>

<div class="my-5 text-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a href="{{ url_for('user.profile', username=current_user.username, page=page_num) }}" class="btn btn-info">{{page_num}}</a>
            {% else %}
                <a href="{{ url_for('user.profile', username=current_user.username, page=page_num) }}" class="btn btn-outline-info">{{page_num}}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
</div>
{% endblock contant %}

flask_module/templates/user/profile_detail.html
{% extends "base.html" %}

{% block title %}
<title>Profile {{user.username}}</title>
{% endblock title %}

{% block contant %}
<div class="container m-5 d-flex">
    <img src="{{ url_for('static', filename='images/'+user.profile_picture) }}" alt="" class="w-25 h-25">
    <div class="ml-5">
        <h3>{{user.username}}</h3>
        <p>{{user.email}}</p>
    </div>
</div>

<div class="m-auto w-75">
    <h1 class="m-auto">{{user.username}}'s Posts</h1>
    {% for post in posts %}
    <div class="jumbotron mt-3 d-flex">
        <img src="{{ url_for('static', filename='images/'+post.image) }}" alt="" class="w-25 h-25">
        <div class="ml-5">
            <p class="lead">{{ post.caption }}</p>
            <hr class="my-4">
            <p>{{ post.created_at }}</p>
            <p>Likes : {{ post.likes|length }}</p>
            <form method="POST" action="{{ url_for('post.add_comment', post_id=post.id) }}" class="comment-form comment-form-{{post.id}} d-none">
                <textarea class="form-control" name="comment" id="" cols="60" rows="5"></textarea>
                <input type="submit" value="Submit" class="btn btn-success mt-2">
            </form>
            <p class="lead">
                <a class="btn btn-primary btn-lg comment-button" data-postid="{{post.id}}" href="javascript:void(0);" role="button">Comment</a>
                <a class="btn btn-info btn-lg view-post-button" id="view-post-{{post.id}}" data-postid="{{post.id}}" href="{{ url_for('post.post_detail', post_id=post.id) }}" role="button">View Post</a>
                <a class="btn btn-warning btn-lg like-button {% for like in post.likes %}{% if like in current_user.like %}disabled{% endif %}{% endfor %}" data-postid="{{post.id}}" href="javascript:void(0);" role="button">Like</a>
            </p>
            <hr class="my-4">
            <h4>Comments :</h4>
            {% for comment in post.comment[0:2] %}
            <h6 class="mt-2">{{comment.user.username}}</h6>
            <p>{{comment.comment}}</p>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</div>

<div class="my-5 text-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a href="{{ url_for('user.profile_detail', username=user.username, page=page_num) }}" class="btn btn-info">{{page_num}}</a>
            {% else %}
                <a href="{{ url_for('user.profile_detail', username=user.username, page=page_num) }}" class="btn btn-outline-info">{{page_num}}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
</div>

{% endblock contant %}

flask_module/templates/user/register.html
{% extends "base.html" %}

{% block title %}
<title>Register</title>
{% endblock title %}

{% block navbar %}
{% endblock navbar %}

{% block contant %}
<div class="container m-auto">
    <h3 class="text-center mt-5">Register Now</h3>
    <form method="POST" action="{{ url_for('user.register') }}" novalidate enctype=multipart/form-data>
        {{form.hidden_tag()}}
        <div class="text-center mt-3">
            {{ form.username.label(class="form-control-label") }}
            {% if form.username.errors %}
                {{ form.username(class="form-control mt-2 is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                        <span>{{error}}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.username(class="form-control mt-2", attr="required=False") }}
            {% endif %}
        </div>
        <div class="text-center mt-3">
            <div class="text-center mt-3">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control mt-2 is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control mt-2", attr="required=False") }}
                {% endif %}
            </div>
        </div>
        <div class="text-center mt-3">
            <div class="text-center mt-3">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control mt-2 is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control mt-2", attr="required=False") }}
                {% endif %}
            </div>
        </div>
        <div class="text-center mt-3">
            <div class="text-center mt-3">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control mt-2 is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control mt-2", attr="required=False") }}
                {% endif %}
            </div>
        </div>
        <div class="text-center mt-3">
            {{ form.profile_picture.label(class="form-control-label w-50") }}
            {{ form.profile_picture(class="form-control-file mt-2 m-auto w-50") }}
            {% if form.profile_picture.errors %}
                {% for error in form.profile_picture.errors %}
                    <span class="text-danger">{{error}}</span><br>
                {% endfor %}
            {% endif %}
        </div>
        <div class="text-center mt-3">
            {{ form.submit(class="btn btn-success mt-2") }}
        </div>
    </form>
    <p class="text-center mt-5">Already registred? Try to <a href="{{ url_for('user.login') }}">Log in.</a></p>
</div>
{% endblock contant %}

flask_module/templates/user/reset_password_request.html
{% extends "base.html" %}

{% block title %}
<title>Reset Password Request</title>
{% endblock title %}

{% block navbar %}
{% endblock navbar %}

{% block contant %}
<div class="container m-auto">
    <h3 class="text-center mt-5">Request to Reset Your Password</h3>
    <form method="POST" action="{{ url_for('user.reset_password_request') }}" novalidate enctype=multipart/form-data>
        {{form.hidden_tag()}}
        <div class="text-center mt-3">
            <div class="text-center mt-3">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control mt-2 is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control mt-2", attr="required=False") }}
                {% endif %}
            </div>
        </div>
        <div class="text-center mt-3">
            {{ form.submit(class="btn btn-success mt-2") }}
            <a href="{{url_for("user.login")}}" class="btn btn-info mt-2">Back</a>
        </div>
    </form>
</div>
{% endblock contant %}