flask_module/customadmin/comments/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, SubmitField, SelectField
from flask_module.posts.models import *

class CustomadminAddCommentForm(FlaskForm):
    comment = StringField("Comment", validators=[validators.DataRequired()])
    post = SelectField("Post", validators=[validators.DataRequired()], choices=[])
    user = SelectField("User", validators=[validators.DataRequired()], choices=[])
    submit = SubmitField("Add Comment")

flask_module/customadmin/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, validators, SubmitField, SelectField, PasswordField, ValidationError
from flask_module.user.models import User
from flask_module.posts.models import *

class CustomadminAddUserForm(FlaskForm):
    username = StringField("Username", validators=[validators.DataRequired(), validators.Length(min=2, max=15)])
    email = StringField("Email", validators=[validators.DataRequired(), validators.Email()])
    profile_picture = FileField("Profile Picture", validators=[FileAllowed(['jpg', 'png'])])
    password = PasswordField("Password", validators=[validators.DataRequired(), validators.Length(min=2, max=10)])
    confirm_password = PasswordField("Confirm Password", validators=[validators.DataRequired(), validators.EqualTo("password")])
    role = SelectField("User Role", validators=[validators.DataRequired()], choices=[])
    submit = SubmitField("Add User")
    
    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError("This username is already exist. Please try another.")
        
    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError("This email is already exist. Please try another.")


class CustomadminEditUserForm(FlaskForm):
    username = StringField("Username", validators=[validators.DataRequired(), validators.Length(min=2, max=15)])
    email = StringField("Email", validators=[validators.DataRequired(), validators.Email()])
    profile_picture = FileField("Profile Picture", validators=[FileAllowed(['jpg', 'png'])])
    role = SelectField("User Role", validators=[validators.DataRequired()], choices=[])
    submit = SubmitField("Update User")
    
    
class CustomadminAddPostForm(FlaskForm):
    image = FileField("Image", validators=[FileAllowed(['jpg', 'png']), validators.DataRequired()])
    caption = StringField("Caption", validators=[validators.DataRequired()])
    user = SelectField("User", validators=[validators.DataRequired()], choices=[])
    submit = SubmitField("Add Post")
    

class CustomadminEditPostForm(FlaskForm):
    image = FileField("Image", validators=[FileAllowed(['jpg', 'png'])])
    caption = StringField("Caption", validators=[])
    submit = SubmitField("Update Post")
    
    
class CustomadminAddCommentForm(FlaskForm):
    comment = StringField("Comment", validators=[validators.DataRequired()])
    post = SelectField("Post", validators=[validators.DataRequired()], choices=[])
    user = SelectField("User", validators=[validators.DataRequired()], choices=[])
    submit = SubmitField("Add Comment")

flask_module/customadmin/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, validators, SubmitField, SelectField, PasswordField, ValidationError
from flask_module.posts.models import *


class CustomadminAddPostForm(FlaskForm):
    image = FileField("Image", validators=[FileAllowed(['jpg', 'png']), validators.DataRequired()])
    caption = StringField("Caption", validators=[validators.DataRequired()])
    user = SelectField("User", validators=[validators.DataRequired()], choices=[])
    submit = SubmitField("Add Post")
    

class CustomadminEditPostForm(FlaskForm):
    image = FileField("Image", validators=[FileAllowed(['jpg', 'png'])])
    caption = StringField("Caption", validators=[])
    submit = SubmitField("Update Post")

flask_module/customadmin/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, validators, SubmitField, SelectField, PasswordField, ValidationError
from flask_module.user.models import User
from flask_module.posts.models import *

class CustomadminAddUserForm(FlaskForm):
    username = StringField("Username", validators=[validators.DataRequired(), validators.Length(min=2, max=15)])
    email = StringField("Email", validators=[validators.DataRequired(), validators.Email()])
    profile_picture = FileField("Profile Picture", validators=[FileAllowed(['jpg', 'png'])])
    password = PasswordField("Password", validators=[validators.DataRequired(), validators.Length(min=2, max=10)])
    confirm_password = PasswordField("Confirm Password", validators=[validators.DataRequired(), validators.EqualTo("password")])
    role = SelectField("User Role", validators=[validators.DataRequired()], choices=[])
    submit = SubmitField("Add User")
    
    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError("This username is already exist. Please try another.")
        
    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError("This email is already exist. Please try another.")


class CustomadminEditUserForm(FlaskForm):
    username = StringField("Username", validators=[validators.DataRequired(), validators.Length(min=2, max=15)])
    email = StringField("Email", validators=[validators.DataRequired(), validators.Email()])
    profile_picture = FileField("Profile Picture", validators=[FileAllowed(['jpg', 'png'])])
    role = SelectField("User Role", validators=[validators.DataRequired()], choices=[])
    submit = SubmitField("Update User")

flask_module/customadmin/comments/routes.py
from ..utiles import *
from flask import render_template, redirect, request, url_for, Blueprint
from flask_module.customadmin.comments.forms import *
from flask_module.user.models import *

comment = Blueprint("comment", __name__, url_prefix="/comment")

@comment.route("/add_comment", methods=["POST", "GET"])
@login_required
@superuser_required
def add_comment():
    form = CustomadminAddCommentForm()
    form.post.choices = [(post.id, (post.user.username, post.caption)) for post in Post.query.all()]
    form.user.choices = [(user.id, user.username) for user in User.query.all()]
    if request.method == "POST":
        if form.validate_on_submit():
            comment = Comments(comment=form.comment.data, user_id=form.user.data, post_id=form.post.data)
            db.session.add(comment)
            db.session.commit()
            return redirect(url_for("customadmin.comment.comments_list"))
    return render_template("customadmin/comments/add_comment.html", form=form)


@comment.route("/<int:comment_id>/comment_update", methods=["POST", "GET"])
@login_required
@superuser_required
def comment_update(comment_id):
    comment_obj = Comments.query.filter_by(id=int(comment_id)).first()
    if request.method == "POST":
        comment = request.form.get("comment")
        comment_obj.comment = comment
        db.session.commit()
        return redirect(url_for('customadmin.comment.comments_list'))
    return render_template("customadmin/comments/update_comment.html", comment=comment_obj)


@comment.route("/comments_list")
@login_required
def comments_list():
    # page = request.args.get("page", 1)
    comments = Comments.query.all()
    return render_template("customadmin/comments/comments_list.html", comments=comments)


@comment.route("/<int:comment_id>/comment_detail")
@login_required
def comment_detail(comment_id):
    comment = Comments.query.filter_by(id=int(comment_id)).first()
    return render_template("customadmin/comments/comment_detail.html", comment=comment)


@comment.route("/<int:comment_id>/delete_comment")
@login_required
@superuser_required
def delete_comment(comment_id):
    comment = Comments.query.filter_by(id=int(comment_id)).first()
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for("customadmin.comment.comments_list"))

flask_module/customadmin/likes/routes.py
from ..utiles import *
from flask import render_template, redirect, url_for, Blueprint
from flask_module.user.models import *
from flask_module.posts.models import Likes

like = Blueprint("like", __name__, url_prefix="/like")

@like.route("/like_list")
@login_required
def like_list():
    # page = request.args.get("page", 1)
    likes = Likes.query.all()
    return render_template("customadmin/likes/likes_list.html", likes=likes)


@like.route("/<int:like_id>/like_detail")
@login_required
def like_detail(like_id):
    like = Likes.query.filter_by(id=int(like_id)).first()
    return render_template("customadmin/likes/like_detail.html", like=like)


@like.route("/<int:like_id>/delete_like")
@login_required
@superuser_required
def delete_like(like_id):
    like = Likes.query.filter_by(id=int(like_id)).first()
    db.session.delete(like)
    db.session.commit()
    return redirect(url_for("customadmin.like_list"))

flask_module/customadmin/posts/routes.py
from ..utiles import *
from flask import render_template, redirect, request, url_for, Blueprint
from flask_module.customadmin.posts.forms import *
from flask_module.user.models import *
import secrets, os

posts = Blueprint("post", __name__, url_prefix="/post")

@posts.route("/add_post", methods=["POST", "GET"])
@login_required
@superuser_required
def add_post():
    form = CustomadminAddPostForm()
    form.user.choices = [(user.id, user.username) for user in User.query.all()]
    if request.method == "POST":
        if form.validate_on_submit():
            print()
            if form.image.data:
                hex_image = secrets.token_hex(8)
                f_name, f_ext = os.path.splitext(form.image.data.filename)
                image_name = hex_image + f_ext
                image_path = os.path.join(app.root_path, 'static\images', image_name)
                form.image.data.save(image_path)
                post = Post(image=image_name, caption=form.caption.data, user_id=form.user.data)
            else:
                post = Post(caption=form.caption.data, user_id=form.user.data)
            db.session.add(post)
            db.session.commit()
            return redirect(url_for("customadmin.post.post_list"))
    return render_template("customadmin/posts/add_post.html", form=form)


@posts.route("/<int:post_id>/post_update", methods=["POST", "GET"])
@login_required
@superuser_required
def post_update(post_id):
    form = CustomadminEditPostForm()
    post = Post.query.filter_by(id=int(post_id)).first()
    if request.method == "POST":
        if form.validate_on_submit():
            if form.image.data:
                hex_image = secrets.token_hex(8)
                f_name, f_ext = os.path.splitext(form.image.data.filename)
                image_name = hex_image + f_ext
                image_path = os.path.join(app.root_path, 'static\images', image_name)
                form.image.data.save(image_path)
                post.image = image_name
            post.caption = form.caption.data
            db.session.commit()
            return redirect(url_for("customadmin.post.post_list"))
    else:
        form.caption.data = post.caption
        return render_template("customadmin/posts/update_post.html", form=form, post=post)


@posts.route("/post_list")
@login_required
def post_list():
    posts = Post.query.all()
    return render_template("customadmin/posts/post_list.html", posts=posts)


@posts.route("/<int:post_id>/post_detail")
@login_required
def post_detail(post_id):
    post = Post.query.filter_by(id=int(post_id)).first()
    return render_template("customadmin/posts/post_detail.html", post=post)


@posts.route("/<int:post_id>/delete_post")
@login_required
@superuser_required
def delete_post(post_id):
    post = Post.query.filter_by(id=int(post_id)).first()
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for("customadmin.post.post_list"))

flask_module/customadmin/routes.py
from flask import Blueprint, render_template, url_for, request, redirect, flash
from flask_module import bcrypt
from flask_module.user.models import User, Role
from flask_module.posts.models import *
from flask_login import current_user, login_user, logout_user
from flask_module.user.forms import LoginForm
from .utiles import login_required

customadmin = Blueprint("customadmin", __name__, url_prefix='/customadmin')

@customadmin.route("/", methods=["POST", "GET"])
@customadmin.route("/login", methods=["POST", "GET"])
def login(): 
    form = LoginForm()
    if request.method == "POST":
        if form.validate_on_submit():
            roles = Role.query.filter(Role.name.in_(["Admin", "Superuser"])).all()
            user = User.query.filter_by(email=form.email.data).first()
            
            if user and bcrypt.check_password_hash(user.password, form.password.data) and user.role in roles:
                login_user(user)
                return redirect(url_for("customadmin.dashboard", username=user.username))
            else:
                flash("User is not able to login.", "danger")
    return render_template("customadmin/login.html", form=form)


@customadmin.route("/dashboard/<string:username>")
@login_required
def dashboard(username):
    users = User.query.filter(User.id != current_user.id)
    return render_template("customadmin/dashboard.html", users=users)


@customadmin.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("customadmin.login"))

flask_module/customadmin/users/__init__.py
from .routes import users

flask_module/customadmin/users/routes.py
from ..utiles import *
from flask import render_template, redirect, request, url_for, Blueprint
from flask_login import current_user
from flask_module.customadmin.users.forms import *
from flask_module.user.models import *
from flask_module import bcrypt 
import secrets, os

users = Blueprint("users", __name__, url_prefix="/user")

@users.route("/add_user", methods=["POST", "GET"])
@login_required
@superuser_required
def add_user():
    form = CustomadminAddUserForm()
    form.role.choices = [role.name for role in Role.query.all()]
    if request.method == "POST":
        if form.validate_on_submit():
            role = Role.query.filter_by(name=form.role.data).first()
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
            if form.profile_picture.data:
                hex_image = secrets.token_hex(8)
                f_name, f_ext = os.path.splitext(form.profile_picture.data.filename)
                image_name = hex_image + f_ext
                image_path = os.path.join(app.root_path, 'static\images', image_name)
                form.profile_picture.data.save(image_path)
                user = User(username=form.username.data, email=form.email.data, profile_picture=image_name, password=hashed_password, role_id=role.id)
            else:
                user = User(username=form.username.data, email=form.email.data, password=hashed_password, role_id=role.id)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('customadmin.dashboard', username=current_user.username))
    return render_template("customadmin/users/add_user.html", form=form)


@users.route("/<int:user_id>/user_update", methods=["POST", "GET"])
@login_required
@superuser_required
def user_update(user_id):
    form = CustomadminEditUserForm()
    user = User.query.filter_by(id=int(user_id)).first()
    form.role.choices = [role.name for role in Role.query.all()]
    if request.method == "POST":
        if form.validate_on_submit():
            if form.profile_picture.data:
                hex_image = secrets.token_hex(8)
                f_name, f_ext = os.path.splitext(form.profile_picture.data.filename)
                image_name = hex_image + f_ext
                image_path = os.path.join(app.root_path, 'static\images', image_name)
                form.profile_picture.data.save(image_path)
                user.profile_picture = image_name
            user.username = form.username.data
            user.email = form.email.data
            role = Role.query.filter_by(name=form.role.data).first()
            user.role = role
            db.session.commit()
            return redirect(url_for("customadmin.dashboard", username=current_user.username))
    else:
        form.username.data = user.username  
        form.email.data = user.email
        form.profile_picture.data = user.profile_picture
        form.role.data = user.role.name
        return render_template("customadmin/users/update_user.html", user=user, form=form)


@users.route("/<int:user_id>/user_detail")
@login_required
def user_detail(user_id):
    user = User.query.filter_by(id=user_id).first()
    return render_template("customadmin/users/user_detail.html", user=user)


@users.route("/<int:user_id>/delete_user")
@login_required
@superuser_required
def delete_user(user_id):
    user = User.query.filter_by(id=int(user_id)).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("customadmin.dashboard", username=current_user.username))

flask_module/templates/customadmin/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{url_for('static', filename="css/datatable.css")}}">
    <link rel="stylesheet" href="{{url_for('static', filename="css/datatable.min.css")}}">
    <title>Dashboard</title>
</head>
<body>

    <style>
        #sidebar {
            height: 900px;
        }
        #module-title {
            margin-top: 80px;
            margin-left: 30px;
        }
        #navbar {
            height: 200px;
        }

    </style>

    <div class="row" id="sidebar">
        <div class="col bg-dark">
            <div id="module-title">
                <h1 class="text-white">Flask Module</h1>
            </div>
            <hr style="background: white">
            <div class="mt-5 text-center">
                <a href="{{url_for('customadmin.dashboard', username=current_user.username)}}"><h3 class="text-white">User</h3></a><br>
                <a href="{{url_for('customadmin.post.post_list')}}"><h3 class="text-white">Post</h3></a><br>
                <a href="{{url_for('customadmin.comment.comments_list')}}"><h3 class="text-white">Comments</h3></a><br>
                <a href="{{url_for('customadmin.like.like_list')}}"><h3 class="text-white">Like</h3></a><br>
            </div>
        </div>

        
        <div class="col-10">

            <div id="navbar" class="bg-secondary">
                <a href="{{url_for('customadmin.logout')}}"><h3 class="float-right px-5 pt-5 text-white">Logout</h3></a>
                <h3 class="text-white pt-4 px-5">User : {{current_user.username}}</h3>
                <h3 class="text-white px-5">Email : {{current_user.email}}</h3>
                <h3 class="text-white px-5">Role : {{current_user.role.name}}</h3>
            </div>

            {% block contant %}

                {% if current_user.role.name == "Superuser" %}
                <div class="text-right">
                    <a href="{{url_for('customadmin.users.add_user')}}"><h3 class="mx-5 my-3 btn btn-dark">Add New User</h3></a>
                </div>
                {% endif %}

            <table id="user-table" class="table table-striped m-auto mt-2">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Username</th>
                    <th scope="col">Email</th>
                    <th scope="col">Profile Picture</th>
                    <th scope="col">Role</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                {% for user in users %}
                  <tr>
                    <th scope="row">{{user.id}}</th>
                    <td>{{user.username}}</td>
                    <td>{{user.email}}</td>
                    <td>{{user.profile_picture}}</td>
                    <td>{{user.role.name}}</td>
                    <td>
                        {% if current_user.role.name == "Superuser" %}
                        <a href="{{url_for('customadmin.users.user_update', user_id=user.id)}}" class="btn btn-warning">Edit</a>
                        <a href="" class="btn btn-danger mx-2 delete-user" data-userid="{{user.id}}">Delete</a>
                        {% endif %}
                        <a href="{{url_for('customadmin.users.user_detail', user_id=user.id)}}" class="btn btn-info">View</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
              {% endblock contant %}
        </div>
        <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
        <script src="{{ url_for('static', filename='js/custom.js') }}"></script>
        <script src="{{url_for('static', filename='js/datatable.js')}}"></script>
        <script src="{{url_for('static', filename='js/datatable.min.js')}}"></script>
    </div>
</body>
</html>

flask_module/templates/customadmin/login.html
{% extends "base.html" %}

{% block title %}
<title>Customadmin Login</title>
{% endblock title %}

{% block navbar %}
{% endblock navbar %}

{% block contant %}
<div class="container m-auto">

    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{category}} m-auto">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <h3 class="text-center mt-5">Customadmin Login</h3>
    <form method="POST" action="{{ url_for('customadmin.login') }}" novalidate>
        {{form.hidden_tag()}}
        <div class="text-center mt-3">
            <div class="text-center mt-3">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control mt-2 is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control mt-2", attr="required=False") }}
                {% endif %}
            </div>
        </div>
        <div class="text-center mt-3">
            <div class="text-center mt-3">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control mt-2 is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control mt-2", attr="required=False") }}
                {% endif %}
            </div>
        </div>
        <div class="text-center mt-3">
            {{ form.submit(class="btn btn-success mt-2") }}
        </div> 
    </form>
</div>
{% endblock contant %}